vfd.settings:
  type: config_object
  label: Views File Downloader Settings
  mapping:
    vfd_table:
      type: sequence
      label: Configurations
      sequence:
        type: mapping
        label: Rule
        mapping:
          view:
            type: string
            label: View
          field:
            type: string
            label: Field
          field_type:
            type: string
            label: Field Type
