floating_block.settings:
  type: config_object
  label: 'Floating block settings'
  mapping:
    blocks:
      type: sequence
      label: 'Floating blocks'
      sequence:
        type: sequence
        sequence:
          type: string
    min_width:
      type: integer
      label: 'Min width'
